# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: Add dependabot pull requests to project

on:
  pull_request:
    types:
      - labeled
env:
  GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
  CREATOR: ${{ github.actor }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issues to project
      env:
          BOOL: ${{ contains( env.CREATOR, 'dependabot' ) }}
      uses: Senzing/github-action-add-issue-to-project@main
      if: ${{ env.BOOL == 'true' }}
      with:
        project: 'https://github.com/orgs/Senzing/projects/2'
        column_name: 'In progress'
