# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: Auto Assign to Project

on:
  issues:
    types: [opened, reopened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/Senzing/projects/2'
        column_name: 'Backlog'
