name: Copy CFTs to S3
on:
  release:
    types:
      - published
jobs:
  Copy_CFTs_to_S3:
    runs-on: ubuntu-latest
    name: Copy CFTs to S3
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SENZING_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SENZING_AWS_ACCESS_SECRET }}
        aws-region: us-east-1
    - name: Get the version of the just published release
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Copy cloudformation-senzing-basic.yaml to S3
      run: aws s3 cp cloudformation-senzing-basic.yaml s3://senzingbuilds/jeffa/cloudformation-senzing-basic.yaml
    - name: Copy cloudformation-senzing-basic.yaml to S3 with version number
      run: aws s3 cp cloudformation-senzing-basic.yaml s3://senzingbuilds/jeffa/cloudformation-senzing-basic-${{ steps.get_version.outputs.VERSION }}.yaml
    - name: Copy cloudformation-senzing-database.yaml to S3
      run: aws s3 cp cloudformation-senzing-database.yaml s3://senzingbuilds/jeffa/cloudformation-senzing-database.yaml
    - name: Copy cloudformation-senzing-database.yaml to S3 with version number
      run: aws s3 cp cloudformation-senzing-database.yaml s3://senzingbuilds/jeffa/cloudformation-senzing-database.yaml-${{ steps.get_version.outputs.VERSION }}.yaml
