name: docker build container

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build-container:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      - name: get repo name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: build docker image
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          image-repository: senzing/${{ steps.repo-basename.outputs.repo }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

  slack-notification:
    needs: [docker-build-container]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.docker-build-container.outputs.status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@179-skern
    with:
      job-status: ${{ needs.docker-build-container.outputs.status }}
