name: docker-push-containers-to-dockerhub.yaml

# on:
#   push:
#     branches:
#       - 143.dockte.2

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker list platforms
        run: docker buildx ls
      - name: Dockerhub login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Debug GITHUB_REF_NAME
        run: echo ${{ github.ref_name }}
      - name: Docker image build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --no-cache \
            --tag senzing/test-ground:latest \
            --tag senzing/test-ground:${{ github.ref_name }} \
            .
