name: docker-build-container.

on:
  push:
    branches:
      - 143.dockter.3

# on:
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:
jobs:
  docker-build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: Senzing/github-action-docker-build-buildx@latest
        with:
          image-repository: test-ground
