name: docker-build-container.

on:
  push:
    branches:
      - 143.dockter.3

# on:
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:
jobs:
  docker-build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: Senzing/github-action-docker-buildx-build@latest
        with:
          build-options: "--push"
          image-repository: senzing/test-ground
          # image-tag: ${{ github.ref_name }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          platforms: "linux/amd64,linux/arm64"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
