# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-linux.yaml

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Senzing API
        uses: Senzing/github-action-install-senzing-api@main
        with:
          senzing-version: staging
