name: make-github-release-assets.yaml

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pwd
      - run: touch /tmp/bob.txt
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/bob.txt
          asset_name: bob2.txt
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
