name: make-go-cmd-version.yaml

#on:
#  release:
#    types: [published]


on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Update cmd/version.go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: PWD
        run: pwd
      - name: Make version.go
        uses: Senzing/github-action-make-go-version-file@main
