name: make-github-release-assets.yaml

on: [push]

# on:
#   push:
#     tags:
#       - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Publish binaries
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pwd
      - name: Did a file get created (before)
        run: ls -la
      - run: echo "Test file" > /tmp/bob.txt
      - name: install create-dmg
        run: brew install create-dmg
      - name: Make a .dmg file
        run: create-dmg "MJD-Application-Installer.dmg"  "tmp/"
      - name: Did a file get created (after)
        run: ls -la

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: /tmp/bob.txt
      #     asset_name: bob2.txt
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: "This is my release text"
