name: make github release assets

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - run: echo "Test file" > /tmp/bob.txt

      - name: upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/bob.txt
          asset_name: bob2.txt
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
