name: make github release assets

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    name: publish binaries
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - run: echo "Test file" > /tmp/bob.txt

      - name: upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/bob.txt
          asset_name: bob2.txt
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"

  slack-notification:
    needs: [build]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.build.outputs.status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v3
    with:
      job-status: ${{ needs.build.outputs.status }}
